# Generated by Django 4.1.4 on 2023-05-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_alter_selected_exam_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_swap_request',
            name='exam',
        ),
    ]
