# Generated by Django 4.1.4 on 2023-04-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='start_end_time',
        ),
        migrations.RemoveField(
            model_name='teacher_availability',
            name='time',
        ),
        migrations.AddField(
            model_name='exam',
            name='end_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='exam',
            name='start_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='teacher_availability',
            name='time_end',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='teacher_availability',
            name='time_start',
            field=models.TimeField(default=None),
        ),
    ]
