# Generated by Django 4.1.4 on 2023-04-03 10:26

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('exam.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='student_courses',
            field=models.ManyToManyField(default=None, to='exam.student'),
        ),
        migrations.AlterField(
            model_name='request_t',
            name='teacher_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', related_query_name='request', to='exam.teacher'),
        ),
    ]
