# Generated by Django 4.1.4 on 2023-04-04 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_teacher_alter_course_student_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_A',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(choices=[('8:00 --> 9:00 AM', '8:00 --> 9:00 AM'), ('9:00 --> 10:00 AM', '8:00 --> 10:00 AM'), ('10:00 --> 11:00 AM', '8:00 --> 11:00 AM'), ('11:00 --> 12:00 PM', '8:00 --> 12:00 PM'), ('12:00 --> 1:00 PM', '8:00 --> 1:00 PM'), ('1:00 --> 2:00 PM', '8:00 --> 2:00 PM'), ('2:00 --> 3:00 PM', '8:00 --> 3:00 PM'), ('3:00 --> 4:00 PM', '8:00 --> 4:00 PM')])),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='request_t',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
